import { describe, expect, test } from "vitest";
import { productionCandidatePolicy } from "../../src/entry/policy.js";
import type { Card } from "../../src/render/card.js";
import { renderReadmeMarkers } from "../../src/render/readme.js";

const card = (github: string, githubId: string): Card => ({
  path: `people/${github}.md`,
  metadata: {
    github,
    githubId,
    avatar: `https://avatars.githubusercontent.com/u/${githubId}?v=4`,
    sourcePr: 1,
  },
  contributor: {
    nickname: github,
    exploring: "Git",
    message: `Hello from ${github}`,
  },
});

describe("README marker renderer", () => {
  test("preserves bytes outside markers and uses explicit comparator and layout", () => {
    const before = "# Hello\n\nmanual bytes: [keep]\n";
    const after = "\n\nfooter bytes\n";
    const readme = `${before}<!-- cards:start -->\nold generated bytes\n<!-- cards:end -->${after}`;
    const result = renderReadmeMarkers(readme, {
      cards: [card("zeta", "2"), card("alpha", "1")],
      compare: (left, right) =>
        left.metadata.github.localeCompare(right.metadata.github),
      renderRegion: (cards) =>
        cards.map((item) => `* ${item.metadata.github}`).join("\n"),
    });

    expect(result).toBe(
      `${before}<!-- cards:start -->\n* alpha\n* zeta\n<!-- cards:end -->${after}`,
    );
  });

  test.each([
    ["missing start", "before\n<!-- cards:end -->\nafter"],
    ["missing end", "before\n<!-- cards:start -->\nafter"],
    [
      "duplicate start",
      "<!-- cards:start -->\n<!-- cards:start -->\n<!-- cards:end -->",
    ],
    [
      "duplicate end",
      "<!-- cards:start -->\n<!-- cards:end -->\n<!-- cards:end -->",
    ],
    ["reversed markers", "<!-- cards:end -->\n<!-- cards:start -->"],
    [
      "malformed marker line",
      "<!-- cards:start --> trailing\n<!-- cards:end -->",
    ],
    [
      "malformed marker alongside valid markers",
      "<!-- cards:start -->\n<!-- cards:end -->\n<!-- cards:start --> trailing",
    ],
  ])("rejects %s", (_reason, readme) => {
    expect(() =>
      renderReadmeMarkers(readme, {
        cards: [],
        compare: () => 0,
        renderRegion: () => "",
      }),
    ).toThrow();
  });

  test("rejects duplicate Card paths or immutable identities before rendering", () => {
    expect(() =>
      renderReadmeMarkers("<!-- cards:start -->\n<!-- cards:end -->", {
        cards: [card("same", "1"), card("same", "2")],
        compare: () => 0,
        renderRegion: () => "",
      }),
    ).toThrow(/duplicate/i);
  });

  test("production Completion Wall renders every required escaped Card field", () => {
    const first = card("alpha", "1");
    first.contributor = {
      nickname: "A*lice",
      exploring: "Git [ops]",
      message: "Hi <all>",
    };
    const result = renderReadmeMarkers(
      "before\n<!-- cards:start -->\n<!-- cards:end -->\nafter\n",
      {
        cards: [card("zeta", "2"), first],
        compare: productionCandidatePolicy.compare,
        renderRegion: productionCandidatePolicy.renderRegion,
      },
    );
    expect(result).toContain("https://avatars.githubusercontent.com/u/1?v=4");
    expect(result).toContain("[alpha](https://github.com/alpha)");
    expect(result).toContain("**A\\*lice**");
    expect(result).toContain("Git \\[ops\\]");
    expect(result).toContain("> Hi \\<all\\>");
    expect(result).toContain("[查看完整 Card](people/alpha.md)");
    expect(result.indexOf("alpha")).toBeLessThan(result.indexOf("zeta"));
    expect(result).toMatch(/^before\n/);
    expect(result).toMatch(/\nafter\n$/);
  });
});
